FROM tiangolo/nginx-rtmp

COPY nginx.conf /etc/nginx/nginx.conf

#docker build -t nginx-rtmp ./
#docker run -d -p 1935:1935 nginx-rtmp 
#rtmp://192.168.1.6/live/<streaming_key>

#In OBS
#server = rtmp://192.168.1.6/live/
#streaming key = test

#In VLC
#URL = rtmp://192.168.1.6/live/test
